#include "sherpa-onnx/c-api/c-api.h"

struct FSherpaAPI {
	typedef const char * (*SherpaOnnxGetVersionStr_ft)();
	SherpaOnnxGetVersionStr_ft SherpaOnnxGetVersionStr_fp = {};
	typedef const char * (*SherpaOnnxGetGitSha1_ft)();
	SherpaOnnxGetGitSha1_ft SherpaOnnxGetGitSha1_fp = {};
	typedef const char * (*SherpaOnnxGetGitDate_ft)();
	SherpaOnnxGetGitDate_ft SherpaOnnxGetGitDate_fp = {};
	typedef int32_t (*SherpaOnnxFileExists_ft)(const char *);
	SherpaOnnxFileExists_ft SherpaOnnxFileExists_fp = {};
	typedef const SherpaOnnxOnlineRecognizer * (*SherpaOnnxCreateOnlineRecognizer_ft)(const SherpaOnnxOnlineRecognizerConfig *);
	SherpaOnnxCreateOnlineRecognizer_ft SherpaOnnxCreateOnlineRecognizer_fp = {};
	typedef void (*SherpaOnnxDestroyOnlineRecognizer_ft)(const SherpaOnnxOnlineRecognizer *);
	SherpaOnnxDestroyOnlineRecognizer_ft SherpaOnnxDestroyOnlineRecognizer_fp = {};
	typedef const SherpaOnnxOnlineStream * (*SherpaOnnxCreateOnlineStream_ft)(const SherpaOnnxOnlineRecognizer *);
	SherpaOnnxCreateOnlineStream_ft SherpaOnnxCreateOnlineStream_fp = {};
	typedef const SherpaOnnxOnlineStream * (*SherpaOnnxCreateOnlineStreamWithHotwords_ft)(const SherpaOnnxOnlineRecognizer *, const char *);
	SherpaOnnxCreateOnlineStreamWithHotwords_ft SherpaOnnxCreateOnlineStreamWithHotwords_fp = {};
	typedef void (*SherpaOnnxDestroyOnlineStream_ft)(const SherpaOnnxOnlineStream *);
	SherpaOnnxDestroyOnlineStream_ft SherpaOnnxDestroyOnlineStream_fp = {};
	typedef void (*SherpaOnnxOnlineStreamAcceptWaveform_ft)(const SherpaOnnxOnlineStream *, int32_t, const float *, int32_t);
	SherpaOnnxOnlineStreamAcceptWaveform_ft SherpaOnnxOnlineStreamAcceptWaveform_fp = {};
	typedef int32_t (*SherpaOnnxIsOnlineStreamReady_ft)(const SherpaOnnxOnlineRecognizer *, const SherpaOnnxOnlineStream *);
	SherpaOnnxIsOnlineStreamReady_ft SherpaOnnxIsOnlineStreamReady_fp = {};
	typedef void (*SherpaOnnxDecodeOnlineStream_ft)(const SherpaOnnxOnlineRecognizer *, const SherpaOnnxOnlineStream *);
	SherpaOnnxDecodeOnlineStream_ft SherpaOnnxDecodeOnlineStream_fp = {};
	typedef void (*SherpaOnnxDecodeMultipleOnlineStreams_ft)(const SherpaOnnxOnlineRecognizer *, const SherpaOnnxOnlineStream **, int32_t);
	SherpaOnnxDecodeMultipleOnlineStreams_ft SherpaOnnxDecodeMultipleOnlineStreams_fp = {};
	typedef const SherpaOnnxOnlineRecognizerResult * (*SherpaOnnxGetOnlineStreamResult_ft)(const SherpaOnnxOnlineRecognizer *, const SherpaOnnxOnlineStream *);
	SherpaOnnxGetOnlineStreamResult_ft SherpaOnnxGetOnlineStreamResult_fp = {};
	typedef void (*SherpaOnnxDestroyOnlineRecognizerResult_ft)(const SherpaOnnxOnlineRecognizerResult *);
	SherpaOnnxDestroyOnlineRecognizerResult_ft SherpaOnnxDestroyOnlineRecognizerResult_fp = {};
	typedef const char * (*SherpaOnnxGetOnlineStreamResultAsJson_ft)(const SherpaOnnxOnlineRecognizer *, const SherpaOnnxOnlineStream *);
	SherpaOnnxGetOnlineStreamResultAsJson_ft SherpaOnnxGetOnlineStreamResultAsJson_fp = {};
	typedef void (*SherpaOnnxDestroyOnlineStreamResultJson_ft)(const char *);
	SherpaOnnxDestroyOnlineStreamResultJson_ft SherpaOnnxDestroyOnlineStreamResultJson_fp = {};
	typedef void (*SherpaOnnxOnlineStreamReset_ft)(const SherpaOnnxOnlineRecognizer *, const SherpaOnnxOnlineStream *);
	SherpaOnnxOnlineStreamReset_ft SherpaOnnxOnlineStreamReset_fp = {};
	typedef void (*SherpaOnnxOnlineStreamInputFinished_ft)(const SherpaOnnxOnlineStream *);
	SherpaOnnxOnlineStreamInputFinished_ft SherpaOnnxOnlineStreamInputFinished_fp = {};
	typedef int32_t (*SherpaOnnxOnlineStreamIsEndpoint_ft)(const SherpaOnnxOnlineRecognizer *, const SherpaOnnxOnlineStream *);
	SherpaOnnxOnlineStreamIsEndpoint_ft SherpaOnnxOnlineStreamIsEndpoint_fp = {};
	typedef const SherpaOnnxDisplay * (*SherpaOnnxCreateDisplay_ft)(int32_t);
	SherpaOnnxCreateDisplay_ft SherpaOnnxCreateDisplay_fp = {};
	typedef void (*SherpaOnnxDestroyDisplay_ft)(const SherpaOnnxDisplay *);
	SherpaOnnxDestroyDisplay_ft SherpaOnnxDestroyDisplay_fp = {};
	typedef void (*SherpaOnnxPrint_ft)(const SherpaOnnxDisplay *, int32_t, const char *);
	SherpaOnnxPrint_ft SherpaOnnxPrint_fp = {};
	typedef const SherpaOnnxOfflineRecognizer * (*SherpaOnnxCreateOfflineRecognizer_ft)(const SherpaOnnxOfflineRecognizerConfig *);
	SherpaOnnxCreateOfflineRecognizer_ft SherpaOnnxCreateOfflineRecognizer_fp = {};
	typedef void (*SherpaOnnxOfflineRecognizerSetConfig_ft)(const SherpaOnnxOfflineRecognizer *, const SherpaOnnxOfflineRecognizerConfig *);
	SherpaOnnxOfflineRecognizerSetConfig_ft SherpaOnnxOfflineRecognizerSetConfig_fp = {};
	typedef void (*SherpaOnnxDestroyOfflineRecognizer_ft)(const SherpaOnnxOfflineRecognizer *);
	SherpaOnnxDestroyOfflineRecognizer_ft SherpaOnnxDestroyOfflineRecognizer_fp = {};
	typedef const SherpaOnnxOfflineStream * (*SherpaOnnxCreateOfflineStream_ft)(const SherpaOnnxOfflineRecognizer *);
	SherpaOnnxCreateOfflineStream_ft SherpaOnnxCreateOfflineStream_fp = {};
	typedef const SherpaOnnxOfflineStream * (*SherpaOnnxCreateOfflineStreamWithHotwords_ft)(const SherpaOnnxOfflineRecognizer *, const char *);
	SherpaOnnxCreateOfflineStreamWithHotwords_ft SherpaOnnxCreateOfflineStreamWithHotwords_fp = {};
	typedef void (*SherpaOnnxDestroyOfflineStream_ft)(const SherpaOnnxOfflineStream *);
	SherpaOnnxDestroyOfflineStream_ft SherpaOnnxDestroyOfflineStream_fp = {};
	typedef void (*SherpaOnnxAcceptWaveformOffline_ft)(const SherpaOnnxOfflineStream *, int32_t, const float *, int32_t);
	SherpaOnnxAcceptWaveformOffline_ft SherpaOnnxAcceptWaveformOffline_fp = {};
	typedef void (*SherpaOnnxDecodeOfflineStream_ft)(const SherpaOnnxOfflineRecognizer *, const SherpaOnnxOfflineStream *);
	SherpaOnnxDecodeOfflineStream_ft SherpaOnnxDecodeOfflineStream_fp = {};
	typedef void (*SherpaOnnxDecodeMultipleOfflineStreams_ft)(const SherpaOnnxOfflineRecognizer *, const SherpaOnnxOfflineStream **, int32_t);
	SherpaOnnxDecodeMultipleOfflineStreams_ft SherpaOnnxDecodeMultipleOfflineStreams_fp = {};
	typedef const SherpaOnnxOfflineRecognizerResult * (*SherpaOnnxGetOfflineStreamResult_ft)(const SherpaOnnxOfflineStream *);
	SherpaOnnxGetOfflineStreamResult_ft SherpaOnnxGetOfflineStreamResult_fp = {};
	typedef void (*SherpaOnnxDestroyOfflineRecognizerResult_ft)(const SherpaOnnxOfflineRecognizerResult *);
	SherpaOnnxDestroyOfflineRecognizerResult_ft SherpaOnnxDestroyOfflineRecognizerResult_fp = {};
	typedef const char * (*SherpaOnnxGetOfflineStreamResultAsJson_ft)(const SherpaOnnxOfflineStream *);
	SherpaOnnxGetOfflineStreamResultAsJson_ft SherpaOnnxGetOfflineStreamResultAsJson_fp = {};
	typedef void (*SherpaOnnxDestroyOfflineStreamResultJson_ft)(const char *);
	SherpaOnnxDestroyOfflineStreamResultJson_ft SherpaOnnxDestroyOfflineStreamResultJson_fp = {};
	typedef const SherpaOnnxKeywordSpotter * (*SherpaOnnxCreateKeywordSpotter_ft)(const SherpaOnnxKeywordSpotterConfig *);
	SherpaOnnxCreateKeywordSpotter_ft SherpaOnnxCreateKeywordSpotter_fp = {};
	typedef void (*SherpaOnnxDestroyKeywordSpotter_ft)(const SherpaOnnxKeywordSpotter *);
	SherpaOnnxDestroyKeywordSpotter_ft SherpaOnnxDestroyKeywordSpotter_fp = {};
	typedef const SherpaOnnxOnlineStream * (*SherpaOnnxCreateKeywordStream_ft)(const SherpaOnnxKeywordSpotter *);
	SherpaOnnxCreateKeywordStream_ft SherpaOnnxCreateKeywordStream_fp = {};
	typedef const SherpaOnnxOnlineStream * (*SherpaOnnxCreateKeywordStreamWithKeywords_ft)(const SherpaOnnxKeywordSpotter *, const char *);
	SherpaOnnxCreateKeywordStreamWithKeywords_ft SherpaOnnxCreateKeywordStreamWithKeywords_fp = {};
	typedef int32_t (*SherpaOnnxIsKeywordStreamReady_ft)(const SherpaOnnxKeywordSpotter *, const SherpaOnnxOnlineStream *);
	SherpaOnnxIsKeywordStreamReady_ft SherpaOnnxIsKeywordStreamReady_fp = {};
	typedef void (*SherpaOnnxDecodeKeywordStream_ft)(const SherpaOnnxKeywordSpotter *, const SherpaOnnxOnlineStream *);
	SherpaOnnxDecodeKeywordStream_ft SherpaOnnxDecodeKeywordStream_fp = {};
	typedef void (*SherpaOnnxResetKeywordStream_ft)(const SherpaOnnxKeywordSpotter *, const SherpaOnnxOnlineStream *);
	SherpaOnnxResetKeywordStream_ft SherpaOnnxResetKeywordStream_fp = {};
	typedef void (*SherpaOnnxDecodeMultipleKeywordStreams_ft)(const SherpaOnnxKeywordSpotter *, const SherpaOnnxOnlineStream **, int32_t);
	SherpaOnnxDecodeMultipleKeywordStreams_ft SherpaOnnxDecodeMultipleKeywordStreams_fp = {};
	typedef const SherpaOnnxKeywordResult * (*SherpaOnnxGetKeywordResult_ft)(const SherpaOnnxKeywordSpotter *, const SherpaOnnxOnlineStream *);
	SherpaOnnxGetKeywordResult_ft SherpaOnnxGetKeywordResult_fp = {};
	typedef void (*SherpaOnnxDestroyKeywordResult_ft)(const SherpaOnnxKeywordResult *);
	SherpaOnnxDestroyKeywordResult_ft SherpaOnnxDestroyKeywordResult_fp = {};
	typedef const char * (*SherpaOnnxGetKeywordResultAsJson_ft)(const SherpaOnnxKeywordSpotter *, const SherpaOnnxOnlineStream *);
	SherpaOnnxGetKeywordResultAsJson_ft SherpaOnnxGetKeywordResultAsJson_fp = {};
	typedef void (*SherpaOnnxFreeKeywordResultJson_ft)(const char *);
	SherpaOnnxFreeKeywordResultJson_ft SherpaOnnxFreeKeywordResultJson_fp = {};
	typedef const SherpaOnnxCircularBuffer * (*SherpaOnnxCreateCircularBuffer_ft)(int32_t);
	SherpaOnnxCreateCircularBuffer_ft SherpaOnnxCreateCircularBuffer_fp = {};
	typedef void (*SherpaOnnxDestroyCircularBuffer_ft)(const SherpaOnnxCircularBuffer *);
	SherpaOnnxDestroyCircularBuffer_ft SherpaOnnxDestroyCircularBuffer_fp = {};
	typedef void (*SherpaOnnxCircularBufferPush_ft)(const SherpaOnnxCircularBuffer *, const float *, int32_t);
	SherpaOnnxCircularBufferPush_ft SherpaOnnxCircularBufferPush_fp = {};
	typedef const float * (*SherpaOnnxCircularBufferGet_ft)(const SherpaOnnxCircularBuffer *, int32_t, int32_t);
	SherpaOnnxCircularBufferGet_ft SherpaOnnxCircularBufferGet_fp = {};
	typedef void (*SherpaOnnxCircularBufferFree_ft)(const float *);
	SherpaOnnxCircularBufferFree_ft SherpaOnnxCircularBufferFree_fp = {};
	typedef void (*SherpaOnnxCircularBufferPop_ft)(const SherpaOnnxCircularBuffer *, int32_t);
	SherpaOnnxCircularBufferPop_ft SherpaOnnxCircularBufferPop_fp = {};
	typedef int32_t (*SherpaOnnxCircularBufferSize_ft)(const SherpaOnnxCircularBuffer *);
	SherpaOnnxCircularBufferSize_ft SherpaOnnxCircularBufferSize_fp = {};
	typedef int32_t (*SherpaOnnxCircularBufferHead_ft)(const SherpaOnnxCircularBuffer *);
	SherpaOnnxCircularBufferHead_ft SherpaOnnxCircularBufferHead_fp = {};
	typedef void (*SherpaOnnxCircularBufferReset_ft)(const SherpaOnnxCircularBuffer *);
	SherpaOnnxCircularBufferReset_ft SherpaOnnxCircularBufferReset_fp = {};
	typedef const SherpaOnnxVoiceActivityDetector * (*SherpaOnnxCreateVoiceActivityDetector_ft)(const SherpaOnnxVadModelConfig *, float);
	SherpaOnnxCreateVoiceActivityDetector_ft SherpaOnnxCreateVoiceActivityDetector_fp = {};
	typedef void (*SherpaOnnxDestroyVoiceActivityDetector_ft)(const SherpaOnnxVoiceActivityDetector *);
	SherpaOnnxDestroyVoiceActivityDetector_ft SherpaOnnxDestroyVoiceActivityDetector_fp = {};
	typedef void (*SherpaOnnxVoiceActivityDetectorAcceptWaveform_ft)(const SherpaOnnxVoiceActivityDetector *, const float *, int32_t);
	SherpaOnnxVoiceActivityDetectorAcceptWaveform_ft SherpaOnnxVoiceActivityDetectorAcceptWaveform_fp = {};
	typedef int32_t (*SherpaOnnxVoiceActivityDetectorEmpty_ft)(const SherpaOnnxVoiceActivityDetector *);
	SherpaOnnxVoiceActivityDetectorEmpty_ft SherpaOnnxVoiceActivityDetectorEmpty_fp = {};
	typedef int32_t (*SherpaOnnxVoiceActivityDetectorDetected_ft)(const SherpaOnnxVoiceActivityDetector *);
	SherpaOnnxVoiceActivityDetectorDetected_ft SherpaOnnxVoiceActivityDetectorDetected_fp = {};
	typedef void (*SherpaOnnxVoiceActivityDetectorPop_ft)(const SherpaOnnxVoiceActivityDetector *);
	SherpaOnnxVoiceActivityDetectorPop_ft SherpaOnnxVoiceActivityDetectorPop_fp = {};
	typedef void (*SherpaOnnxVoiceActivityDetectorClear_ft)(const SherpaOnnxVoiceActivityDetector *);
	SherpaOnnxVoiceActivityDetectorClear_ft SherpaOnnxVoiceActivityDetectorClear_fp = {};
	typedef const SherpaOnnxSpeechSegment * (*SherpaOnnxVoiceActivityDetectorFront_ft)(const SherpaOnnxVoiceActivityDetector *);
	SherpaOnnxVoiceActivityDetectorFront_ft SherpaOnnxVoiceActivityDetectorFront_fp = {};
	typedef void (*SherpaOnnxDestroySpeechSegment_ft)(const SherpaOnnxSpeechSegment *);
	SherpaOnnxDestroySpeechSegment_ft SherpaOnnxDestroySpeechSegment_fp = {};
	typedef void (*SherpaOnnxVoiceActivityDetectorReset_ft)(const SherpaOnnxVoiceActivityDetector *);
	SherpaOnnxVoiceActivityDetectorReset_ft SherpaOnnxVoiceActivityDetectorReset_fp = {};
	typedef void (*SherpaOnnxVoiceActivityDetectorFlush_ft)(const SherpaOnnxVoiceActivityDetector *);
	SherpaOnnxVoiceActivityDetectorFlush_ft SherpaOnnxVoiceActivityDetectorFlush_fp = {};
	typedef const SherpaOnnxOfflineTts * (*SherpaOnnxCreateOfflineTts_ft)(const SherpaOnnxOfflineTtsConfig *);
	SherpaOnnxCreateOfflineTts_ft SherpaOnnxCreateOfflineTts_fp = {};
	typedef void (*SherpaOnnxDestroyOfflineTts_ft)(const SherpaOnnxOfflineTts *);
	SherpaOnnxDestroyOfflineTts_ft SherpaOnnxDestroyOfflineTts_fp = {};
	typedef int32_t (*SherpaOnnxOfflineTtsSampleRate_ft)(const SherpaOnnxOfflineTts *);
	SherpaOnnxOfflineTtsSampleRate_ft SherpaOnnxOfflineTtsSampleRate_fp = {};
	typedef int32_t (*SherpaOnnxOfflineTtsNumSpeakers_ft)(const SherpaOnnxOfflineTts *);
	SherpaOnnxOfflineTtsNumSpeakers_ft SherpaOnnxOfflineTtsNumSpeakers_fp = {};
	typedef const SherpaOnnxGeneratedAudio * (*SherpaOnnxOfflineTtsGenerate_ft)(const SherpaOnnxOfflineTts *, const char *, int32_t, float);
	SherpaOnnxOfflineTtsGenerate_ft SherpaOnnxOfflineTtsGenerate_fp = {};
	typedef const SherpaOnnxGeneratedAudio * (*SherpaOnnxOfflineTtsGenerateWithCallback_ft)(const SherpaOnnxOfflineTts *, const char *, int32_t, float, SherpaOnnxGeneratedAudioCallback);
	SherpaOnnxOfflineTtsGenerateWithCallback_ft SherpaOnnxOfflineTtsGenerateWithCallback_fp = {};
	typedef const SherpaOnnxGeneratedAudio * (*SherpaOnnxOfflineTtsGenerateWithProgressCallback_ft)(const SherpaOnnxOfflineTts *, const char *, int32_t, float, SherpaOnnxGeneratedAudioProgressCallback);
	SherpaOnnxOfflineTtsGenerateWithProgressCallback_ft SherpaOnnxOfflineTtsGenerateWithProgressCallback_fp = {};
	typedef const SherpaOnnxGeneratedAudio * (*SherpaOnnxOfflineTtsGenerateWithProgressCallbackWithArg_ft)(const SherpaOnnxOfflineTts *, const char *, int32_t, float, SherpaOnnxGeneratedAudioProgressCallbackWithArg, void *);
	SherpaOnnxOfflineTtsGenerateWithProgressCallbackWithArg_ft SherpaOnnxOfflineTtsGenerateWithProgressCallbackWithArg_fp = {};
	typedef const SherpaOnnxGeneratedAudio * (*SherpaOnnxOfflineTtsGenerateWithCallbackWithArg_ft)(const SherpaOnnxOfflineTts *, const char *, int32_t, float, SherpaOnnxGeneratedAudioCallbackWithArg, void *);
	SherpaOnnxOfflineTtsGenerateWithCallbackWithArg_ft SherpaOnnxOfflineTtsGenerateWithCallbackWithArg_fp = {};
	typedef const SherpaOnnxGeneratedAudio * (*SherpaOnnxOfflineTtsGenerateWithZipvoice_ft)(const SherpaOnnxOfflineTts *, const char *, const char *, const float *, int32_t, int32_t, float, int32_t);
	SherpaOnnxOfflineTtsGenerateWithZipvoice_ft SherpaOnnxOfflineTtsGenerateWithZipvoice_fp = {};
	typedef void (*SherpaOnnxDestroyOfflineTtsGeneratedAudio_ft)(const SherpaOnnxGeneratedAudio *);
	SherpaOnnxDestroyOfflineTtsGeneratedAudio_ft SherpaOnnxDestroyOfflineTtsGeneratedAudio_fp = {};
	typedef int32_t (*SherpaOnnxWriteWave_ft)(const float *, int32_t, int32_t, const char *);
	SherpaOnnxWriteWave_ft SherpaOnnxWriteWave_fp = {};
	typedef int64_t (*SherpaOnnxWaveFileSize_ft)(int32_t);
	SherpaOnnxWaveFileSize_ft SherpaOnnxWaveFileSize_fp = {};
	typedef void (*SherpaOnnxWriteWaveToBuffer_ft)(const float *, int32_t, int32_t, char *);
	SherpaOnnxWriteWaveToBuffer_ft SherpaOnnxWriteWaveToBuffer_fp = {};
	typedef const SherpaOnnxWave * (*SherpaOnnxReadWave_ft)(const char *);
	SherpaOnnxReadWave_ft SherpaOnnxReadWave_fp = {};
	typedef const SherpaOnnxWave * (*SherpaOnnxReadWaveFromBinaryData_ft)(const char *, int32_t);
	SherpaOnnxReadWaveFromBinaryData_ft SherpaOnnxReadWaveFromBinaryData_fp = {};
	typedef void (*SherpaOnnxFreeWave_ft)(const SherpaOnnxWave *);
	SherpaOnnxFreeWave_ft SherpaOnnxFreeWave_fp = {};
	typedef const SherpaOnnxSpokenLanguageIdentification * (*SherpaOnnxCreateSpokenLanguageIdentification_ft)(const SherpaOnnxSpokenLanguageIdentificationConfig *);
	SherpaOnnxCreateSpokenLanguageIdentification_ft SherpaOnnxCreateSpokenLanguageIdentification_fp = {};
	typedef void (*SherpaOnnxDestroySpokenLanguageIdentification_ft)(const SherpaOnnxSpokenLanguageIdentification *);
	SherpaOnnxDestroySpokenLanguageIdentification_ft SherpaOnnxDestroySpokenLanguageIdentification_fp = {};
	typedef SherpaOnnxOfflineStream * (*SherpaOnnxSpokenLanguageIdentificationCreateOfflineStream_ft)(const SherpaOnnxSpokenLanguageIdentification *);
	SherpaOnnxSpokenLanguageIdentificationCreateOfflineStream_ft SherpaOnnxSpokenLanguageIdentificationCreateOfflineStream_fp = {};
	typedef const SherpaOnnxSpokenLanguageIdentificationResult * (*SherpaOnnxSpokenLanguageIdentificationCompute_ft)(const SherpaOnnxSpokenLanguageIdentification *, const SherpaOnnxOfflineStream *);
	SherpaOnnxSpokenLanguageIdentificationCompute_ft SherpaOnnxSpokenLanguageIdentificationCompute_fp = {};
	typedef void (*SherpaOnnxDestroySpokenLanguageIdentificationResult_ft)(const SherpaOnnxSpokenLanguageIdentificationResult *);
	SherpaOnnxDestroySpokenLanguageIdentificationResult_ft SherpaOnnxDestroySpokenLanguageIdentificationResult_fp = {};
	typedef const SherpaOnnxSpeakerEmbeddingExtractor * (*SherpaOnnxCreateSpeakerEmbeddingExtractor_ft)(const SherpaOnnxSpeakerEmbeddingExtractorConfig *);
	SherpaOnnxCreateSpeakerEmbeddingExtractor_ft SherpaOnnxCreateSpeakerEmbeddingExtractor_fp = {};
	typedef void (*SherpaOnnxDestroySpeakerEmbeddingExtractor_ft)(const SherpaOnnxSpeakerEmbeddingExtractor *);
	SherpaOnnxDestroySpeakerEmbeddingExtractor_ft SherpaOnnxDestroySpeakerEmbeddingExtractor_fp = {};
	typedef int32_t (*SherpaOnnxSpeakerEmbeddingExtractorDim_ft)(const SherpaOnnxSpeakerEmbeddingExtractor *);
	SherpaOnnxSpeakerEmbeddingExtractorDim_ft SherpaOnnxSpeakerEmbeddingExtractorDim_fp = {};
	typedef const SherpaOnnxOnlineStream * (*SherpaOnnxSpeakerEmbeddingExtractorCreateStream_ft)(const SherpaOnnxSpeakerEmbeddingExtractor *);
	SherpaOnnxSpeakerEmbeddingExtractorCreateStream_ft SherpaOnnxSpeakerEmbeddingExtractorCreateStream_fp = {};
	typedef int32_t (*SherpaOnnxSpeakerEmbeddingExtractorIsReady_ft)(const SherpaOnnxSpeakerEmbeddingExtractor *, const SherpaOnnxOnlineStream *);
	SherpaOnnxSpeakerEmbeddingExtractorIsReady_ft SherpaOnnxSpeakerEmbeddingExtractorIsReady_fp = {};
	typedef const float * (*SherpaOnnxSpeakerEmbeddingExtractorComputeEmbedding_ft)(const SherpaOnnxSpeakerEmbeddingExtractor *, const SherpaOnnxOnlineStream *);
	SherpaOnnxSpeakerEmbeddingExtractorComputeEmbedding_ft SherpaOnnxSpeakerEmbeddingExtractorComputeEmbedding_fp = {};
	typedef void (*SherpaOnnxSpeakerEmbeddingExtractorDestroyEmbedding_ft)(const float *);
	SherpaOnnxSpeakerEmbeddingExtractorDestroyEmbedding_ft SherpaOnnxSpeakerEmbeddingExtractorDestroyEmbedding_fp = {};
	typedef const SherpaOnnxSpeakerEmbeddingManager * (*SherpaOnnxCreateSpeakerEmbeddingManager_ft)(int32_t);
	SherpaOnnxCreateSpeakerEmbeddingManager_ft SherpaOnnxCreateSpeakerEmbeddingManager_fp = {};
	typedef void (*SherpaOnnxDestroySpeakerEmbeddingManager_ft)(const SherpaOnnxSpeakerEmbeddingManager *);
	SherpaOnnxDestroySpeakerEmbeddingManager_ft SherpaOnnxDestroySpeakerEmbeddingManager_fp = {};
	typedef int32_t (*SherpaOnnxSpeakerEmbeddingManagerAdd_ft)(const SherpaOnnxSpeakerEmbeddingManager *, const char *, const float *);
	SherpaOnnxSpeakerEmbeddingManagerAdd_ft SherpaOnnxSpeakerEmbeddingManagerAdd_fp = {};
	typedef int32_t (*SherpaOnnxSpeakerEmbeddingManagerAddList_ft)(const SherpaOnnxSpeakerEmbeddingManager *, const char *, const float **);
	SherpaOnnxSpeakerEmbeddingManagerAddList_ft SherpaOnnxSpeakerEmbeddingManagerAddList_fp = {};
	typedef int32_t (*SherpaOnnxSpeakerEmbeddingManagerAddListFlattened_ft)(const SherpaOnnxSpeakerEmbeddingManager *, const char *, const float *, int32_t);
	SherpaOnnxSpeakerEmbeddingManagerAddListFlattened_ft SherpaOnnxSpeakerEmbeddingManagerAddListFlattened_fp = {};
	typedef int32_t (*SherpaOnnxSpeakerEmbeddingManagerRemove_ft)(const SherpaOnnxSpeakerEmbeddingManager *, const char *);
	SherpaOnnxSpeakerEmbeddingManagerRemove_ft SherpaOnnxSpeakerEmbeddingManagerRemove_fp = {};
	typedef const char * (*SherpaOnnxSpeakerEmbeddingManagerSearch_ft)(const SherpaOnnxSpeakerEmbeddingManager *, const float *, float);
	SherpaOnnxSpeakerEmbeddingManagerSearch_ft SherpaOnnxSpeakerEmbeddingManagerSearch_fp = {};
	typedef void (*SherpaOnnxSpeakerEmbeddingManagerFreeSearch_ft)(const char *);
	SherpaOnnxSpeakerEmbeddingManagerFreeSearch_ft SherpaOnnxSpeakerEmbeddingManagerFreeSearch_fp = {};
	typedef const SherpaOnnxSpeakerEmbeddingManagerBestMatchesResult * (*SherpaOnnxSpeakerEmbeddingManagerGetBestMatches_ft)(const SherpaOnnxSpeakerEmbeddingManager *, const float *, float, int32_t);
	SherpaOnnxSpeakerEmbeddingManagerGetBestMatches_ft SherpaOnnxSpeakerEmbeddingManagerGetBestMatches_fp = {};
	typedef void (*SherpaOnnxSpeakerEmbeddingManagerFreeBestMatches_ft)(const SherpaOnnxSpeakerEmbeddingManagerBestMatchesResult *);
	SherpaOnnxSpeakerEmbeddingManagerFreeBestMatches_ft SherpaOnnxSpeakerEmbeddingManagerFreeBestMatches_fp = {};
	typedef int32_t (*SherpaOnnxSpeakerEmbeddingManagerVerify_ft)(const SherpaOnnxSpeakerEmbeddingManager *, const char *, const float *, float);
	SherpaOnnxSpeakerEmbeddingManagerVerify_ft SherpaOnnxSpeakerEmbeddingManagerVerify_fp = {};
	typedef int32_t (*SherpaOnnxSpeakerEmbeddingManagerContains_ft)(const SherpaOnnxSpeakerEmbeddingManager *, const char *);
	SherpaOnnxSpeakerEmbeddingManagerContains_ft SherpaOnnxSpeakerEmbeddingManagerContains_fp = {};
	typedef int32_t (*SherpaOnnxSpeakerEmbeddingManagerNumSpeakers_ft)(const SherpaOnnxSpeakerEmbeddingManager *);
	SherpaOnnxSpeakerEmbeddingManagerNumSpeakers_ft SherpaOnnxSpeakerEmbeddingManagerNumSpeakers_fp = {};
	typedef const char *const * (*SherpaOnnxSpeakerEmbeddingManagerGetAllSpeakers_ft)(const SherpaOnnxSpeakerEmbeddingManager *);
	SherpaOnnxSpeakerEmbeddingManagerGetAllSpeakers_ft SherpaOnnxSpeakerEmbeddingManagerGetAllSpeakers_fp = {};
	typedef void (*SherpaOnnxSpeakerEmbeddingManagerFreeAllSpeakers_ft)(const char *const *);
	SherpaOnnxSpeakerEmbeddingManagerFreeAllSpeakers_ft SherpaOnnxSpeakerEmbeddingManagerFreeAllSpeakers_fp = {};
	typedef const SherpaOnnxAudioTagging * (*SherpaOnnxCreateAudioTagging_ft)(const SherpaOnnxAudioTaggingConfig *);
	SherpaOnnxCreateAudioTagging_ft SherpaOnnxCreateAudioTagging_fp = {};
	typedef void (*SherpaOnnxDestroyAudioTagging_ft)(const SherpaOnnxAudioTagging *);
	SherpaOnnxDestroyAudioTagging_ft SherpaOnnxDestroyAudioTagging_fp = {};
	typedef const SherpaOnnxOfflineStream * (*SherpaOnnxAudioTaggingCreateOfflineStream_ft)(const SherpaOnnxAudioTagging *);
	SherpaOnnxAudioTaggingCreateOfflineStream_ft SherpaOnnxAudioTaggingCreateOfflineStream_fp = {};
	typedef const SherpaOnnxAudioEvent *const * (*SherpaOnnxAudioTaggingCompute_ft)(const SherpaOnnxAudioTagging *, const SherpaOnnxOfflineStream *, int32_t);
	SherpaOnnxAudioTaggingCompute_ft SherpaOnnxAudioTaggingCompute_fp = {};
	typedef void (*SherpaOnnxAudioTaggingFreeResults_ft)(const SherpaOnnxAudioEvent *const *);
	SherpaOnnxAudioTaggingFreeResults_ft SherpaOnnxAudioTaggingFreeResults_fp = {};
	typedef const SherpaOnnxOfflinePunctuation * (*SherpaOnnxCreateOfflinePunctuation_ft)(const SherpaOnnxOfflinePunctuationConfig *);
	SherpaOnnxCreateOfflinePunctuation_ft SherpaOnnxCreateOfflinePunctuation_fp = {};
	typedef void (*SherpaOnnxDestroyOfflinePunctuation_ft)(const SherpaOnnxOfflinePunctuation *);
	SherpaOnnxDestroyOfflinePunctuation_ft SherpaOnnxDestroyOfflinePunctuation_fp = {};
	typedef const SherpaOnnxOnlinePunctuation * (*SherpaOnnxCreateOnlinePunctuation_ft)(const SherpaOnnxOnlinePunctuationConfig *);
	SherpaOnnxCreateOnlinePunctuation_ft SherpaOnnxCreateOnlinePunctuation_fp = {};
	typedef void (*SherpaOnnxDestroyOnlinePunctuation_ft)(const SherpaOnnxOnlinePunctuation *);
	SherpaOnnxDestroyOnlinePunctuation_ft SherpaOnnxDestroyOnlinePunctuation_fp = {};
	typedef const char * (*SherpaOnnxOnlinePunctuationAddPunct_ft)(const SherpaOnnxOnlinePunctuation *, const char *);
	SherpaOnnxOnlinePunctuationAddPunct_ft SherpaOnnxOnlinePunctuationAddPunct_fp = {};
	typedef void (*SherpaOnnxOnlinePunctuationFreeText_ft)(const char *);
	SherpaOnnxOnlinePunctuationFreeText_ft SherpaOnnxOnlinePunctuationFreeText_fp = {};
	typedef const SherpaOnnxLinearResampler * (*SherpaOnnxCreateLinearResampler_ft)(int32_t, int32_t, float, int32_t);
	SherpaOnnxCreateLinearResampler_ft SherpaOnnxCreateLinearResampler_fp = {};
	typedef void (*SherpaOnnxDestroyLinearResampler_ft)(const SherpaOnnxLinearResampler *);
	SherpaOnnxDestroyLinearResampler_ft SherpaOnnxDestroyLinearResampler_fp = {};
	typedef void (*SherpaOnnxLinearResamplerReset_ft)(const SherpaOnnxLinearResampler *);
	SherpaOnnxLinearResamplerReset_ft SherpaOnnxLinearResamplerReset_fp = {};
	typedef const SherpaOnnxResampleOut * (*SherpaOnnxLinearResamplerResample_ft)(const SherpaOnnxLinearResampler *, const float *, int32_t, int32_t);
	SherpaOnnxLinearResamplerResample_ft SherpaOnnxLinearResamplerResample_fp = {};
	typedef void (*SherpaOnnxLinearResamplerResampleFree_ft)(const SherpaOnnxResampleOut *);
	SherpaOnnxLinearResamplerResampleFree_ft SherpaOnnxLinearResamplerResampleFree_fp = {};
	typedef int32_t (*SherpaOnnxLinearResamplerResampleGetInputSampleRate_ft)(const SherpaOnnxLinearResampler *);
	SherpaOnnxLinearResamplerResampleGetInputSampleRate_ft SherpaOnnxLinearResamplerResampleGetInputSampleRate_fp = {};
	typedef int32_t (*SherpaOnnxLinearResamplerResampleGetOutputSampleRate_ft)(const SherpaOnnxLinearResampler *);
	SherpaOnnxLinearResamplerResampleGetOutputSampleRate_ft SherpaOnnxLinearResamplerResampleGetOutputSampleRate_fp = {};
	typedef const SherpaOnnxOfflineSpeakerDiarization * (*SherpaOnnxCreateOfflineSpeakerDiarization_ft)(const SherpaOnnxOfflineSpeakerDiarizationConfig *);
	SherpaOnnxCreateOfflineSpeakerDiarization_ft SherpaOnnxCreateOfflineSpeakerDiarization_fp = {};
	typedef void (*SherpaOnnxDestroyOfflineSpeakerDiarization_ft)(const SherpaOnnxOfflineSpeakerDiarization *);
	SherpaOnnxDestroyOfflineSpeakerDiarization_ft SherpaOnnxDestroyOfflineSpeakerDiarization_fp = {};
	typedef int32_t (*SherpaOnnxOfflineSpeakerDiarizationGetSampleRate_ft)(const SherpaOnnxOfflineSpeakerDiarization *);
	SherpaOnnxOfflineSpeakerDiarizationGetSampleRate_ft SherpaOnnxOfflineSpeakerDiarizationGetSampleRate_fp = {};
	typedef void (*SherpaOnnxOfflineSpeakerDiarizationSetConfig_ft)(const SherpaOnnxOfflineSpeakerDiarization *, const SherpaOnnxOfflineSpeakerDiarizationConfig *);
	SherpaOnnxOfflineSpeakerDiarizationSetConfig_ft SherpaOnnxOfflineSpeakerDiarizationSetConfig_fp = {};
	typedef int32_t (*SherpaOnnxOfflineSpeakerDiarizationResultGetNumSpeakers_ft)(const SherpaOnnxOfflineSpeakerDiarizationResult *);
	SherpaOnnxOfflineSpeakerDiarizationResultGetNumSpeakers_ft SherpaOnnxOfflineSpeakerDiarizationResultGetNumSpeakers_fp = {};
	typedef int32_t (*SherpaOnnxOfflineSpeakerDiarizationResultGetNumSegments_ft)(const SherpaOnnxOfflineSpeakerDiarizationResult *);
	SherpaOnnxOfflineSpeakerDiarizationResultGetNumSegments_ft SherpaOnnxOfflineSpeakerDiarizationResultGetNumSegments_fp = {};
	typedef const SherpaOnnxOfflineSpeakerDiarizationSegment * (*SherpaOnnxOfflineSpeakerDiarizationResultSortByStartTime_ft)(const SherpaOnnxOfflineSpeakerDiarizationResult *);
	SherpaOnnxOfflineSpeakerDiarizationResultSortByStartTime_ft SherpaOnnxOfflineSpeakerDiarizationResultSortByStartTime_fp = {};
	typedef void (*SherpaOnnxOfflineSpeakerDiarizationDestroySegment_ft)(const SherpaOnnxOfflineSpeakerDiarizationSegment *);
	SherpaOnnxOfflineSpeakerDiarizationDestroySegment_ft SherpaOnnxOfflineSpeakerDiarizationDestroySegment_fp = {};
	typedef const SherpaOnnxOfflineSpeakerDiarizationResult * (*SherpaOnnxOfflineSpeakerDiarizationProcess_ft)(const SherpaOnnxOfflineSpeakerDiarization *, const float *, int32_t);
	SherpaOnnxOfflineSpeakerDiarizationProcess_ft SherpaOnnxOfflineSpeakerDiarizationProcess_fp = {};
	typedef const SherpaOnnxOfflineSpeakerDiarizationResult * (*SherpaOnnxOfflineSpeakerDiarizationProcessWithCallback_ft)(const SherpaOnnxOfflineSpeakerDiarization *, const float *, int32_t, SherpaOnnxOfflineSpeakerDiarizationProgressCallback, void *);
	SherpaOnnxOfflineSpeakerDiarizationProcessWithCallback_ft SherpaOnnxOfflineSpeakerDiarizationProcessWithCallback_fp = {};
	typedef const SherpaOnnxOfflineSpeakerDiarizationResult * (*SherpaOnnxOfflineSpeakerDiarizationProcessWithCallbackNoArg_ft)(const SherpaOnnxOfflineSpeakerDiarization *, const float *, int32_t, SherpaOnnxOfflineSpeakerDiarizationProgressCallbackNoArg);
	SherpaOnnxOfflineSpeakerDiarizationProcessWithCallbackNoArg_ft SherpaOnnxOfflineSpeakerDiarizationProcessWithCallbackNoArg_fp = {};
	typedef void (*SherpaOnnxOfflineSpeakerDiarizationDestroyResult_ft)(const SherpaOnnxOfflineSpeakerDiarizationResult *);
	SherpaOnnxOfflineSpeakerDiarizationDestroyResult_ft SherpaOnnxOfflineSpeakerDiarizationDestroyResult_fp = {};
	typedef const SherpaOnnxOfflineSpeechDenoiser * (*SherpaOnnxCreateOfflineSpeechDenoiser_ft)(const SherpaOnnxOfflineSpeechDenoiserConfig *);
	SherpaOnnxCreateOfflineSpeechDenoiser_ft SherpaOnnxCreateOfflineSpeechDenoiser_fp = {};
	typedef void (*SherpaOnnxDestroyOfflineSpeechDenoiser_ft)(const SherpaOnnxOfflineSpeechDenoiser *);
	SherpaOnnxDestroyOfflineSpeechDenoiser_ft SherpaOnnxDestroyOfflineSpeechDenoiser_fp = {};
	typedef int32_t (*SherpaOnnxOfflineSpeechDenoiserGetSampleRate_ft)(const SherpaOnnxOfflineSpeechDenoiser *);
	SherpaOnnxOfflineSpeechDenoiserGetSampleRate_ft SherpaOnnxOfflineSpeechDenoiserGetSampleRate_fp = {};
	typedef const SherpaOnnxDenoisedAudio * (*SherpaOnnxOfflineSpeechDenoiserRun_ft)(const SherpaOnnxOfflineSpeechDenoiser *, const float *, int32_t, int32_t);
	SherpaOnnxOfflineSpeechDenoiserRun_ft SherpaOnnxOfflineSpeechDenoiserRun_fp = {};
	typedef void (*SherpaOnnxDestroyDenoisedAudio_ft)(const SherpaOnnxDenoisedAudio *);
	SherpaOnnxDestroyDenoisedAudio_ft SherpaOnnxDestroyDenoisedAudio_fp = {};
};

inline bool LoadSherpaAPI(const FString& DllPath, FSherpaAPI& OutAPI) {
	void* DllHandle = FPlatformProcess::GetDllHandle(*DllPath); if (!DllHandle) return false;
	OutAPI.SherpaOnnxGetVersionStr_fp = (FSherpaAPI::SherpaOnnxGetVersionStr_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxGetVersionStr"));
	OutAPI.SherpaOnnxGetGitSha1_fp = (FSherpaAPI::SherpaOnnxGetGitSha1_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxGetGitSha1"));
	OutAPI.SherpaOnnxGetGitDate_fp = (FSherpaAPI::SherpaOnnxGetGitDate_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxGetGitDate"));
	OutAPI.SherpaOnnxFileExists_fp = (FSherpaAPI::SherpaOnnxFileExists_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxFileExists"));
	OutAPI.SherpaOnnxCreateOnlineRecognizer_fp = (FSherpaAPI::SherpaOnnxCreateOnlineRecognizer_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCreateOnlineRecognizer"));
	OutAPI.SherpaOnnxDestroyOnlineRecognizer_fp = (FSherpaAPI::SherpaOnnxDestroyOnlineRecognizer_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroyOnlineRecognizer"));
	OutAPI.SherpaOnnxCreateOnlineStream_fp = (FSherpaAPI::SherpaOnnxCreateOnlineStream_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCreateOnlineStream"));
	OutAPI.SherpaOnnxCreateOnlineStreamWithHotwords_fp = (FSherpaAPI::SherpaOnnxCreateOnlineStreamWithHotwords_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCreateOnlineStreamWithHotwords"));
	OutAPI.SherpaOnnxDestroyOnlineStream_fp = (FSherpaAPI::SherpaOnnxDestroyOnlineStream_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroyOnlineStream"));
	OutAPI.SherpaOnnxOnlineStreamAcceptWaveform_fp = (FSherpaAPI::SherpaOnnxOnlineStreamAcceptWaveform_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOnlineStreamAcceptWaveform"));
	OutAPI.SherpaOnnxIsOnlineStreamReady_fp = (FSherpaAPI::SherpaOnnxIsOnlineStreamReady_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxIsOnlineStreamReady"));
	OutAPI.SherpaOnnxDecodeOnlineStream_fp = (FSherpaAPI::SherpaOnnxDecodeOnlineStream_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDecodeOnlineStream"));
	OutAPI.SherpaOnnxDecodeMultipleOnlineStreams_fp = (FSherpaAPI::SherpaOnnxDecodeMultipleOnlineStreams_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDecodeMultipleOnlineStreams"));
	OutAPI.SherpaOnnxGetOnlineStreamResult_fp = (FSherpaAPI::SherpaOnnxGetOnlineStreamResult_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxGetOnlineStreamResult"));
	OutAPI.SherpaOnnxDestroyOnlineRecognizerResult_fp = (FSherpaAPI::SherpaOnnxDestroyOnlineRecognizerResult_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroyOnlineRecognizerResult"));
	OutAPI.SherpaOnnxGetOnlineStreamResultAsJson_fp = (FSherpaAPI::SherpaOnnxGetOnlineStreamResultAsJson_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxGetOnlineStreamResultAsJson"));
	OutAPI.SherpaOnnxDestroyOnlineStreamResultJson_fp = (FSherpaAPI::SherpaOnnxDestroyOnlineStreamResultJson_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroyOnlineStreamResultJson"));
	OutAPI.SherpaOnnxOnlineStreamReset_fp = (FSherpaAPI::SherpaOnnxOnlineStreamReset_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOnlineStreamReset"));
	OutAPI.SherpaOnnxOnlineStreamInputFinished_fp = (FSherpaAPI::SherpaOnnxOnlineStreamInputFinished_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOnlineStreamInputFinished"));
	OutAPI.SherpaOnnxOnlineStreamIsEndpoint_fp = (FSherpaAPI::SherpaOnnxOnlineStreamIsEndpoint_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOnlineStreamIsEndpoint"));
	OutAPI.SherpaOnnxCreateDisplay_fp = (FSherpaAPI::SherpaOnnxCreateDisplay_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCreateDisplay"));
	OutAPI.SherpaOnnxDestroyDisplay_fp = (FSherpaAPI::SherpaOnnxDestroyDisplay_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroyDisplay"));
	OutAPI.SherpaOnnxPrint_fp = (FSherpaAPI::SherpaOnnxPrint_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxPrint"));
	OutAPI.SherpaOnnxCreateOfflineRecognizer_fp = (FSherpaAPI::SherpaOnnxCreateOfflineRecognizer_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCreateOfflineRecognizer"));
	OutAPI.SherpaOnnxOfflineRecognizerSetConfig_fp = (FSherpaAPI::SherpaOnnxOfflineRecognizerSetConfig_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOfflineRecognizerSetConfig"));
	OutAPI.SherpaOnnxDestroyOfflineRecognizer_fp = (FSherpaAPI::SherpaOnnxDestroyOfflineRecognizer_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroyOfflineRecognizer"));
	OutAPI.SherpaOnnxCreateOfflineStream_fp = (FSherpaAPI::SherpaOnnxCreateOfflineStream_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCreateOfflineStream"));
	OutAPI.SherpaOnnxCreateOfflineStreamWithHotwords_fp = (FSherpaAPI::SherpaOnnxCreateOfflineStreamWithHotwords_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCreateOfflineStreamWithHotwords"));
	OutAPI.SherpaOnnxDestroyOfflineStream_fp = (FSherpaAPI::SherpaOnnxDestroyOfflineStream_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroyOfflineStream"));
	OutAPI.SherpaOnnxAcceptWaveformOffline_fp = (FSherpaAPI::SherpaOnnxAcceptWaveformOffline_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxAcceptWaveformOffline"));
	OutAPI.SherpaOnnxDecodeOfflineStream_fp = (FSherpaAPI::SherpaOnnxDecodeOfflineStream_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDecodeOfflineStream"));
	OutAPI.SherpaOnnxDecodeMultipleOfflineStreams_fp = (FSherpaAPI::SherpaOnnxDecodeMultipleOfflineStreams_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDecodeMultipleOfflineStreams"));
	OutAPI.SherpaOnnxGetOfflineStreamResult_fp = (FSherpaAPI::SherpaOnnxGetOfflineStreamResult_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxGetOfflineStreamResult"));
	OutAPI.SherpaOnnxDestroyOfflineRecognizerResult_fp = (FSherpaAPI::SherpaOnnxDestroyOfflineRecognizerResult_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroyOfflineRecognizerResult"));
	OutAPI.SherpaOnnxGetOfflineStreamResultAsJson_fp = (FSherpaAPI::SherpaOnnxGetOfflineStreamResultAsJson_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxGetOfflineStreamResultAsJson"));
	OutAPI.SherpaOnnxDestroyOfflineStreamResultJson_fp = (FSherpaAPI::SherpaOnnxDestroyOfflineStreamResultJson_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroyOfflineStreamResultJson"));
	OutAPI.SherpaOnnxCreateKeywordSpotter_fp = (FSherpaAPI::SherpaOnnxCreateKeywordSpotter_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCreateKeywordSpotter"));
	OutAPI.SherpaOnnxDestroyKeywordSpotter_fp = (FSherpaAPI::SherpaOnnxDestroyKeywordSpotter_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroyKeywordSpotter"));
	OutAPI.SherpaOnnxCreateKeywordStream_fp = (FSherpaAPI::SherpaOnnxCreateKeywordStream_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCreateKeywordStream"));
	OutAPI.SherpaOnnxCreateKeywordStreamWithKeywords_fp = (FSherpaAPI::SherpaOnnxCreateKeywordStreamWithKeywords_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCreateKeywordStreamWithKeywords"));
	OutAPI.SherpaOnnxIsKeywordStreamReady_fp = (FSherpaAPI::SherpaOnnxIsKeywordStreamReady_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxIsKeywordStreamReady"));
	OutAPI.SherpaOnnxDecodeKeywordStream_fp = (FSherpaAPI::SherpaOnnxDecodeKeywordStream_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDecodeKeywordStream"));
	OutAPI.SherpaOnnxResetKeywordStream_fp = (FSherpaAPI::SherpaOnnxResetKeywordStream_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxResetKeywordStream"));
	OutAPI.SherpaOnnxDecodeMultipleKeywordStreams_fp = (FSherpaAPI::SherpaOnnxDecodeMultipleKeywordStreams_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDecodeMultipleKeywordStreams"));
	OutAPI.SherpaOnnxGetKeywordResult_fp = (FSherpaAPI::SherpaOnnxGetKeywordResult_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxGetKeywordResult"));
	OutAPI.SherpaOnnxDestroyKeywordResult_fp = (FSherpaAPI::SherpaOnnxDestroyKeywordResult_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroyKeywordResult"));
	OutAPI.SherpaOnnxGetKeywordResultAsJson_fp = (FSherpaAPI::SherpaOnnxGetKeywordResultAsJson_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxGetKeywordResultAsJson"));
	OutAPI.SherpaOnnxFreeKeywordResultJson_fp = (FSherpaAPI::SherpaOnnxFreeKeywordResultJson_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxFreeKeywordResultJson"));
	OutAPI.SherpaOnnxCreateCircularBuffer_fp = (FSherpaAPI::SherpaOnnxCreateCircularBuffer_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCreateCircularBuffer"));
	OutAPI.SherpaOnnxDestroyCircularBuffer_fp = (FSherpaAPI::SherpaOnnxDestroyCircularBuffer_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroyCircularBuffer"));
	OutAPI.SherpaOnnxCircularBufferPush_fp = (FSherpaAPI::SherpaOnnxCircularBufferPush_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCircularBufferPush"));
	OutAPI.SherpaOnnxCircularBufferGet_fp = (FSherpaAPI::SherpaOnnxCircularBufferGet_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCircularBufferGet"));
	OutAPI.SherpaOnnxCircularBufferFree_fp = (FSherpaAPI::SherpaOnnxCircularBufferFree_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCircularBufferFree"));
	OutAPI.SherpaOnnxCircularBufferPop_fp = (FSherpaAPI::SherpaOnnxCircularBufferPop_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCircularBufferPop"));
	OutAPI.SherpaOnnxCircularBufferSize_fp = (FSherpaAPI::SherpaOnnxCircularBufferSize_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCircularBufferSize"));
	OutAPI.SherpaOnnxCircularBufferHead_fp = (FSherpaAPI::SherpaOnnxCircularBufferHead_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCircularBufferHead"));
	OutAPI.SherpaOnnxCircularBufferReset_fp = (FSherpaAPI::SherpaOnnxCircularBufferReset_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCircularBufferReset"));
	OutAPI.SherpaOnnxCreateVoiceActivityDetector_fp = (FSherpaAPI::SherpaOnnxCreateVoiceActivityDetector_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCreateVoiceActivityDetector"));
	OutAPI.SherpaOnnxDestroyVoiceActivityDetector_fp = (FSherpaAPI::SherpaOnnxDestroyVoiceActivityDetector_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroyVoiceActivityDetector"));
	OutAPI.SherpaOnnxVoiceActivityDetectorAcceptWaveform_fp = (FSherpaAPI::SherpaOnnxVoiceActivityDetectorAcceptWaveform_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxVoiceActivityDetectorAcceptWaveform"));
	OutAPI.SherpaOnnxVoiceActivityDetectorEmpty_fp = (FSherpaAPI::SherpaOnnxVoiceActivityDetectorEmpty_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxVoiceActivityDetectorEmpty"));
	OutAPI.SherpaOnnxVoiceActivityDetectorDetected_fp = (FSherpaAPI::SherpaOnnxVoiceActivityDetectorDetected_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxVoiceActivityDetectorDetected"));
	OutAPI.SherpaOnnxVoiceActivityDetectorPop_fp = (FSherpaAPI::SherpaOnnxVoiceActivityDetectorPop_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxVoiceActivityDetectorPop"));
	OutAPI.SherpaOnnxVoiceActivityDetectorClear_fp = (FSherpaAPI::SherpaOnnxVoiceActivityDetectorClear_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxVoiceActivityDetectorClear"));
	OutAPI.SherpaOnnxVoiceActivityDetectorFront_fp = (FSherpaAPI::SherpaOnnxVoiceActivityDetectorFront_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxVoiceActivityDetectorFront"));
	OutAPI.SherpaOnnxDestroySpeechSegment_fp = (FSherpaAPI::SherpaOnnxDestroySpeechSegment_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroySpeechSegment"));
	OutAPI.SherpaOnnxVoiceActivityDetectorReset_fp = (FSherpaAPI::SherpaOnnxVoiceActivityDetectorReset_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxVoiceActivityDetectorReset"));
	OutAPI.SherpaOnnxVoiceActivityDetectorFlush_fp = (FSherpaAPI::SherpaOnnxVoiceActivityDetectorFlush_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxVoiceActivityDetectorFlush"));
	OutAPI.SherpaOnnxCreateOfflineTts_fp = (FSherpaAPI::SherpaOnnxCreateOfflineTts_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCreateOfflineTts"));
	OutAPI.SherpaOnnxDestroyOfflineTts_fp = (FSherpaAPI::SherpaOnnxDestroyOfflineTts_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroyOfflineTts"));
	OutAPI.SherpaOnnxOfflineTtsSampleRate_fp = (FSherpaAPI::SherpaOnnxOfflineTtsSampleRate_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOfflineTtsSampleRate"));
	OutAPI.SherpaOnnxOfflineTtsNumSpeakers_fp = (FSherpaAPI::SherpaOnnxOfflineTtsNumSpeakers_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOfflineTtsNumSpeakers"));
	OutAPI.SherpaOnnxOfflineTtsGenerate_fp = (FSherpaAPI::SherpaOnnxOfflineTtsGenerate_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOfflineTtsGenerate"));
	OutAPI.SherpaOnnxOfflineTtsGenerateWithCallback_fp = (FSherpaAPI::SherpaOnnxOfflineTtsGenerateWithCallback_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOfflineTtsGenerateWithCallback"));
	OutAPI.SherpaOnnxOfflineTtsGenerateWithProgressCallback_fp = (FSherpaAPI::SherpaOnnxOfflineTtsGenerateWithProgressCallback_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOfflineTtsGenerateWithProgressCallback"));
	OutAPI.SherpaOnnxOfflineTtsGenerateWithProgressCallbackWithArg_fp = (FSherpaAPI::SherpaOnnxOfflineTtsGenerateWithProgressCallbackWithArg_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOfflineTtsGenerateWithProgressCallbackWithArg"));
	OutAPI.SherpaOnnxOfflineTtsGenerateWithCallbackWithArg_fp = (FSherpaAPI::SherpaOnnxOfflineTtsGenerateWithCallbackWithArg_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOfflineTtsGenerateWithCallbackWithArg"));
	OutAPI.SherpaOnnxOfflineTtsGenerateWithZipvoice_fp = (FSherpaAPI::SherpaOnnxOfflineTtsGenerateWithZipvoice_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOfflineTtsGenerateWithZipvoice"));
	OutAPI.SherpaOnnxDestroyOfflineTtsGeneratedAudio_fp = (FSherpaAPI::SherpaOnnxDestroyOfflineTtsGeneratedAudio_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroyOfflineTtsGeneratedAudio"));
	OutAPI.SherpaOnnxWriteWave_fp = (FSherpaAPI::SherpaOnnxWriteWave_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxWriteWave"));
	OutAPI.SherpaOnnxWaveFileSize_fp = (FSherpaAPI::SherpaOnnxWaveFileSize_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxWaveFileSize"));
	OutAPI.SherpaOnnxWriteWaveToBuffer_fp = (FSherpaAPI::SherpaOnnxWriteWaveToBuffer_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxWriteWaveToBuffer"));
	OutAPI.SherpaOnnxReadWave_fp = (FSherpaAPI::SherpaOnnxReadWave_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxReadWave"));
	OutAPI.SherpaOnnxReadWaveFromBinaryData_fp = (FSherpaAPI::SherpaOnnxReadWaveFromBinaryData_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxReadWaveFromBinaryData"));
	OutAPI.SherpaOnnxFreeWave_fp = (FSherpaAPI::SherpaOnnxFreeWave_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxFreeWave"));
	OutAPI.SherpaOnnxCreateSpokenLanguageIdentification_fp = (FSherpaAPI::SherpaOnnxCreateSpokenLanguageIdentification_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCreateSpokenLanguageIdentification"));
	OutAPI.SherpaOnnxDestroySpokenLanguageIdentification_fp = (FSherpaAPI::SherpaOnnxDestroySpokenLanguageIdentification_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroySpokenLanguageIdentification"));
	OutAPI.SherpaOnnxSpokenLanguageIdentificationCreateOfflineStream_fp = (FSherpaAPI::SherpaOnnxSpokenLanguageIdentificationCreateOfflineStream_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxSpokenLanguageIdentificationCreateOfflineStream"));
	OutAPI.SherpaOnnxSpokenLanguageIdentificationCompute_fp = (FSherpaAPI::SherpaOnnxSpokenLanguageIdentificationCompute_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxSpokenLanguageIdentificationCompute"));
	OutAPI.SherpaOnnxDestroySpokenLanguageIdentificationResult_fp = (FSherpaAPI::SherpaOnnxDestroySpokenLanguageIdentificationResult_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroySpokenLanguageIdentificationResult"));
	OutAPI.SherpaOnnxCreateSpeakerEmbeddingExtractor_fp = (FSherpaAPI::SherpaOnnxCreateSpeakerEmbeddingExtractor_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCreateSpeakerEmbeddingExtractor"));
	OutAPI.SherpaOnnxDestroySpeakerEmbeddingExtractor_fp = (FSherpaAPI::SherpaOnnxDestroySpeakerEmbeddingExtractor_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroySpeakerEmbeddingExtractor"));
	OutAPI.SherpaOnnxSpeakerEmbeddingExtractorDim_fp = (FSherpaAPI::SherpaOnnxSpeakerEmbeddingExtractorDim_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxSpeakerEmbeddingExtractorDim"));
	OutAPI.SherpaOnnxSpeakerEmbeddingExtractorCreateStream_fp = (FSherpaAPI::SherpaOnnxSpeakerEmbeddingExtractorCreateStream_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxSpeakerEmbeddingExtractorCreateStream"));
	OutAPI.SherpaOnnxSpeakerEmbeddingExtractorIsReady_fp = (FSherpaAPI::SherpaOnnxSpeakerEmbeddingExtractorIsReady_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxSpeakerEmbeddingExtractorIsReady"));
	OutAPI.SherpaOnnxSpeakerEmbeddingExtractorComputeEmbedding_fp = (FSherpaAPI::SherpaOnnxSpeakerEmbeddingExtractorComputeEmbedding_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxSpeakerEmbeddingExtractorComputeEmbedding"));
	OutAPI.SherpaOnnxSpeakerEmbeddingExtractorDestroyEmbedding_fp = (FSherpaAPI::SherpaOnnxSpeakerEmbeddingExtractorDestroyEmbedding_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxSpeakerEmbeddingExtractorDestroyEmbedding"));
	OutAPI.SherpaOnnxCreateSpeakerEmbeddingManager_fp = (FSherpaAPI::SherpaOnnxCreateSpeakerEmbeddingManager_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCreateSpeakerEmbeddingManager"));
	OutAPI.SherpaOnnxDestroySpeakerEmbeddingManager_fp = (FSherpaAPI::SherpaOnnxDestroySpeakerEmbeddingManager_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroySpeakerEmbeddingManager"));
	OutAPI.SherpaOnnxSpeakerEmbeddingManagerAdd_fp = (FSherpaAPI::SherpaOnnxSpeakerEmbeddingManagerAdd_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxSpeakerEmbeddingManagerAdd"));
	OutAPI.SherpaOnnxSpeakerEmbeddingManagerAddList_fp = (FSherpaAPI::SherpaOnnxSpeakerEmbeddingManagerAddList_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxSpeakerEmbeddingManagerAddList"));
	OutAPI.SherpaOnnxSpeakerEmbeddingManagerAddListFlattened_fp = (FSherpaAPI::SherpaOnnxSpeakerEmbeddingManagerAddListFlattened_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxSpeakerEmbeddingManagerAddListFlattened"));
	OutAPI.SherpaOnnxSpeakerEmbeddingManagerRemove_fp = (FSherpaAPI::SherpaOnnxSpeakerEmbeddingManagerRemove_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxSpeakerEmbeddingManagerRemove"));
	OutAPI.SherpaOnnxSpeakerEmbeddingManagerSearch_fp = (FSherpaAPI::SherpaOnnxSpeakerEmbeddingManagerSearch_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxSpeakerEmbeddingManagerSearch"));
	OutAPI.SherpaOnnxSpeakerEmbeddingManagerFreeSearch_fp = (FSherpaAPI::SherpaOnnxSpeakerEmbeddingManagerFreeSearch_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxSpeakerEmbeddingManagerFreeSearch"));
	OutAPI.SherpaOnnxSpeakerEmbeddingManagerGetBestMatches_fp = (FSherpaAPI::SherpaOnnxSpeakerEmbeddingManagerGetBestMatches_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxSpeakerEmbeddingManagerGetBestMatches"));
	OutAPI.SherpaOnnxSpeakerEmbeddingManagerFreeBestMatches_fp = (FSherpaAPI::SherpaOnnxSpeakerEmbeddingManagerFreeBestMatches_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxSpeakerEmbeddingManagerFreeBestMatches"));
	OutAPI.SherpaOnnxSpeakerEmbeddingManagerVerify_fp = (FSherpaAPI::SherpaOnnxSpeakerEmbeddingManagerVerify_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxSpeakerEmbeddingManagerVerify"));
	OutAPI.SherpaOnnxSpeakerEmbeddingManagerContains_fp = (FSherpaAPI::SherpaOnnxSpeakerEmbeddingManagerContains_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxSpeakerEmbeddingManagerContains"));
	OutAPI.SherpaOnnxSpeakerEmbeddingManagerNumSpeakers_fp = (FSherpaAPI::SherpaOnnxSpeakerEmbeddingManagerNumSpeakers_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxSpeakerEmbeddingManagerNumSpeakers"));
	OutAPI.SherpaOnnxSpeakerEmbeddingManagerGetAllSpeakers_fp = (FSherpaAPI::SherpaOnnxSpeakerEmbeddingManagerGetAllSpeakers_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxSpeakerEmbeddingManagerGetAllSpeakers"));
	OutAPI.SherpaOnnxSpeakerEmbeddingManagerFreeAllSpeakers_fp = (FSherpaAPI::SherpaOnnxSpeakerEmbeddingManagerFreeAllSpeakers_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxSpeakerEmbeddingManagerFreeAllSpeakers"));
	OutAPI.SherpaOnnxCreateAudioTagging_fp = (FSherpaAPI::SherpaOnnxCreateAudioTagging_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCreateAudioTagging"));
	OutAPI.SherpaOnnxDestroyAudioTagging_fp = (FSherpaAPI::SherpaOnnxDestroyAudioTagging_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroyAudioTagging"));
	OutAPI.SherpaOnnxAudioTaggingCreateOfflineStream_fp = (FSherpaAPI::SherpaOnnxAudioTaggingCreateOfflineStream_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxAudioTaggingCreateOfflineStream"));
	OutAPI.SherpaOnnxAudioTaggingCompute_fp = (FSherpaAPI::SherpaOnnxAudioTaggingCompute_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxAudioTaggingCompute"));
	OutAPI.SherpaOnnxAudioTaggingFreeResults_fp = (FSherpaAPI::SherpaOnnxAudioTaggingFreeResults_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxAudioTaggingFreeResults"));
	OutAPI.SherpaOnnxCreateOfflinePunctuation_fp = (FSherpaAPI::SherpaOnnxCreateOfflinePunctuation_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCreateOfflinePunctuation"));
	OutAPI.SherpaOnnxDestroyOfflinePunctuation_fp = (FSherpaAPI::SherpaOnnxDestroyOfflinePunctuation_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroyOfflinePunctuation"));
	OutAPI.SherpaOnnxCreateOnlinePunctuation_fp = (FSherpaAPI::SherpaOnnxCreateOnlinePunctuation_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCreateOnlinePunctuation"));
	OutAPI.SherpaOnnxDestroyOnlinePunctuation_fp = (FSherpaAPI::SherpaOnnxDestroyOnlinePunctuation_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroyOnlinePunctuation"));
	OutAPI.SherpaOnnxOnlinePunctuationAddPunct_fp = (FSherpaAPI::SherpaOnnxOnlinePunctuationAddPunct_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOnlinePunctuationAddPunct"));
	OutAPI.SherpaOnnxOnlinePunctuationFreeText_fp = (FSherpaAPI::SherpaOnnxOnlinePunctuationFreeText_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOnlinePunctuationFreeText"));
	OutAPI.SherpaOnnxCreateLinearResampler_fp = (FSherpaAPI::SherpaOnnxCreateLinearResampler_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCreateLinearResampler"));
	OutAPI.SherpaOnnxDestroyLinearResampler_fp = (FSherpaAPI::SherpaOnnxDestroyLinearResampler_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroyLinearResampler"));
	OutAPI.SherpaOnnxLinearResamplerReset_fp = (FSherpaAPI::SherpaOnnxLinearResamplerReset_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxLinearResamplerReset"));
	OutAPI.SherpaOnnxLinearResamplerResample_fp = (FSherpaAPI::SherpaOnnxLinearResamplerResample_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxLinearResamplerResample"));
	OutAPI.SherpaOnnxLinearResamplerResampleFree_fp = (FSherpaAPI::SherpaOnnxLinearResamplerResampleFree_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxLinearResamplerResampleFree"));
	OutAPI.SherpaOnnxLinearResamplerResampleGetInputSampleRate_fp = (FSherpaAPI::SherpaOnnxLinearResamplerResampleGetInputSampleRate_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxLinearResamplerResampleGetInputSampleRate"));
	OutAPI.SherpaOnnxLinearResamplerResampleGetOutputSampleRate_fp = (FSherpaAPI::SherpaOnnxLinearResamplerResampleGetOutputSampleRate_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxLinearResamplerResampleGetOutputSampleRate"));
	OutAPI.SherpaOnnxCreateOfflineSpeakerDiarization_fp = (FSherpaAPI::SherpaOnnxCreateOfflineSpeakerDiarization_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCreateOfflineSpeakerDiarization"));
	OutAPI.SherpaOnnxDestroyOfflineSpeakerDiarization_fp = (FSherpaAPI::SherpaOnnxDestroyOfflineSpeakerDiarization_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroyOfflineSpeakerDiarization"));
	OutAPI.SherpaOnnxOfflineSpeakerDiarizationGetSampleRate_fp = (FSherpaAPI::SherpaOnnxOfflineSpeakerDiarizationGetSampleRate_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOfflineSpeakerDiarizationGetSampleRate"));
	OutAPI.SherpaOnnxOfflineSpeakerDiarizationSetConfig_fp = (FSherpaAPI::SherpaOnnxOfflineSpeakerDiarizationSetConfig_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOfflineSpeakerDiarizationSetConfig"));
	OutAPI.SherpaOnnxOfflineSpeakerDiarizationResultGetNumSpeakers_fp = (FSherpaAPI::SherpaOnnxOfflineSpeakerDiarizationResultGetNumSpeakers_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOfflineSpeakerDiarizationResultGetNumSpeakers"));
	OutAPI.SherpaOnnxOfflineSpeakerDiarizationResultGetNumSegments_fp = (FSherpaAPI::SherpaOnnxOfflineSpeakerDiarizationResultGetNumSegments_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOfflineSpeakerDiarizationResultGetNumSegments"));
	OutAPI.SherpaOnnxOfflineSpeakerDiarizationResultSortByStartTime_fp = (FSherpaAPI::SherpaOnnxOfflineSpeakerDiarizationResultSortByStartTime_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOfflineSpeakerDiarizationResultSortByStartTime"));
	OutAPI.SherpaOnnxOfflineSpeakerDiarizationDestroySegment_fp = (FSherpaAPI::SherpaOnnxOfflineSpeakerDiarizationDestroySegment_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOfflineSpeakerDiarizationDestroySegment"));
	OutAPI.SherpaOnnxOfflineSpeakerDiarizationProcess_fp = (FSherpaAPI::SherpaOnnxOfflineSpeakerDiarizationProcess_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOfflineSpeakerDiarizationProcess"));
	OutAPI.SherpaOnnxOfflineSpeakerDiarizationProcessWithCallback_fp = (FSherpaAPI::SherpaOnnxOfflineSpeakerDiarizationProcessWithCallback_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOfflineSpeakerDiarizationProcessWithCallback"));
	OutAPI.SherpaOnnxOfflineSpeakerDiarizationProcessWithCallbackNoArg_fp = (FSherpaAPI::SherpaOnnxOfflineSpeakerDiarizationProcessWithCallbackNoArg_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOfflineSpeakerDiarizationProcessWithCallbackNoArg"));
	OutAPI.SherpaOnnxOfflineSpeakerDiarizationDestroyResult_fp = (FSherpaAPI::SherpaOnnxOfflineSpeakerDiarizationDestroyResult_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOfflineSpeakerDiarizationDestroyResult"));
	OutAPI.SherpaOnnxCreateOfflineSpeechDenoiser_fp = (FSherpaAPI::SherpaOnnxCreateOfflineSpeechDenoiser_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxCreateOfflineSpeechDenoiser"));
	OutAPI.SherpaOnnxDestroyOfflineSpeechDenoiser_fp = (FSherpaAPI::SherpaOnnxDestroyOfflineSpeechDenoiser_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroyOfflineSpeechDenoiser"));
	OutAPI.SherpaOnnxOfflineSpeechDenoiserGetSampleRate_fp = (FSherpaAPI::SherpaOnnxOfflineSpeechDenoiserGetSampleRate_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOfflineSpeechDenoiserGetSampleRate"));
	OutAPI.SherpaOnnxOfflineSpeechDenoiserRun_fp = (FSherpaAPI::SherpaOnnxOfflineSpeechDenoiserRun_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxOfflineSpeechDenoiserRun"));
	OutAPI.SherpaOnnxDestroyDenoisedAudio_fp = (FSherpaAPI::SherpaOnnxDestroyDenoisedAudio_ft)FPlatformProcess::GetDllExport(DllHandle, TEXT("SherpaOnnxDestroyDenoisedAudio"));
	return OutAPI.SherpaOnnxGetVersionStr_fp ? true : false;
}
